### ISSUE TITLE
Make HANDLE_TAKEN error message more redable

### ISSUE THREAD

**Issue by bigint** [aave/lens-api-examples#52]
<img width="580" alt="Screenshot 2022-04-17 at 7 49 34 PM" src="https://user-images.githubusercontent.com/69431456/163718553-7f4b0b4d-93cf-4531-b3fd-e8ac926f3f8f.png">

We use the error message that comes from API, so it would be great if we have some good error messages like we have for other areas (collect module error messages are good `You need to follow profile to collect`)

cc @damarnez @joshstevens19

**Comment by joshstevens19** [comment]
A handled error on server endpoints will always be handled like this. A thrown error which prints out as you said above is a dev error (as it’s not expected your client to call it if it does not conform to standards aka it throws) but this handle error is a expected error which can happen without the client if calling it when it should not, the UI needs to handle this. Because the server should not assume the language the UI is working with this is up to the UI to handle and define the message not the server.
